from openai import OpenAI
import backoff
import time

class Agent:
    def __init__(self, name: str, temperature: float, openai_api_key: str, sleep_time: float=0) -> None:
        """Create an agent

        Args:
            name (str): name of this agent
            temperature (float): higher values make the output more random, while lower values make it more focused and deterministic
            openai_api_key (str): OpenAI API key
            sleep_time (float): sleep because of rate limits
        """
        self.client = OpenAI(
            api_key=openai_api_key,
            base_url="https://api.deepseek.com/v1"
        )
        self.name = name
        self.temperature = temperature
        self.openai_api_key = openai_api_key
        self.memory_lst = []
        self.sleep_time = sleep_time
        # 固定使用deepseek模型
        self.model = "deepseek-chat"

    @backoff.on_exception(backoff.expo, Exception, max_tries=20)
    def query(self, messages: "list[dict]", max_tokens: int, temperature: float) -> str:
        """make a query

        Args:
            messages (list[dict]): chat history in turbo format
            max_tokens (int): max token in api call
            temperature (float): sampling temperature

        Returns:
            str: the return msg
        """
        time.sleep(self.sleep_time)
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=messages,
                temperature=temperature,
                max_tokens=max_tokens,
            )
            gen = response.choices[0].message.content
            return gen

        except Exception as e:
            # 简化异常处理
            print(f"Error: {e}")
            raise

    def set_meta_prompt(self, meta_prompt: str):
        """Set the meta_prompt

        Args:
            meta_prompt (str): the meta prompt
        """
        self.memory_lst.append({"role": "system", "content": f"{meta_prompt}"})

    def add_event(self, event: str):
        """Add an new event in the memory

        Args:
            event (str): string that describe the event.
        """
        self.memory_lst.append({"role": "user", "content": f"{event}"})

    def add_memory(self, memory: str):
        """Monologue in the memory

        Args:
            memory (str): string that generated by the model in the last round.
        """
        self.memory_lst.append({"role": "assistant", "content": f"{memory}"})
        print(f"----- {self.name} -----\n{memory}\n")

    def ask(self, temperature: float=None):
        """Query for answer

        Args:
        """
        
        def count_tokens(text):
            try:
                import tiktoken
                encoding = tiktoken.get_encoding("cl100k_base")
                return len(encoding.encode(text))
            except:
                # 如果tiktoken不可用，使用简单的估算方法
                return len(text) // 4
        
        # 计算上下文token数量
        num_context_token = sum([count_tokens(m["content"]) for m in self.memory_lst])
        # 设置一个合理的max_token值
        max_token = 2000
        return self.query(self.memory_lst, max_token, temperature=temperature if temperature else self.temperature)